[package]
name = "rusty_rockets"
version = "0.1.0"
authors = ["Daniel Mancebo <dani.mancebo_3@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32"
rand = "0.7.0"
vector2d = "2.2.0"